print("Hello World.") 
print("Hello avinash")
print("Hello Again!") 
print("I like typing this."), print("This is fun.")
print('Yay! Printing.')
print("I'd much rather you 'not'.")
print('I "ssaid" do not touch this.')
